// Shared domain types. Mirror Prisma enums so the app compiles and runs even
// when the Prisma client is not generated yet (no DATABASE_URL configured).

export const Platforms = ["twitter", "instagram", "youtube", "tiktok", "reddit"] as const;
export type Platform = (typeof Platforms)[number];

export const EngagementTrends = ["rising", "stable", "declining"] as const;
export type EngagementTrend = (typeof EngagementTrends)[number];

export const SuggestedActions = [
  "like",
  "comment",
  "repost",
  "follow",
  "dm",
  "invite",
] as const;
export type SuggestedAction = (typeof SuggestedActions)[number];

export interface SocialLink {
  platform: string; // "youtube" | "twitter" | "instagram" | ... | "website"
  url: string;
  label?: string; // optional display label (e.g. handle)
}

export interface Influencer {
  id: string;
  handle: string;
  platform: Platform;
  niche: string;
  followerCount: number;
  postingFrequency: number;
  engagementTrend: EngagementTrend;
  relevanceScore: number;
  socialLinks: SocialLink[];
  createdAt: string;
  updatedAt: string;
}

export interface Hashtag {
  id: string;
  name: string;
  platform: Platform;
  relevanceScore: number;
  lastCheckedAt: string;
  createdAt: string;
}

export interface Post {
  id: string;
  content: string;
  creatorHandle: string;
  platform: Platform;
  engagementVelocity: number;
  relevanceScore: number;
  opportunityScore: number;
  suggestedAction: SuggestedAction;
  createdAt: string;
  url?: string;
  sourceHashtag?: string;
  // Optional enrichment: harvested social links for this post's creator, joined
  // from the matching Influencer record by (platform, handle). Populated by the
  // opportunities API for display on the feed; not persisted on Post itself.
  creatorSocialLinks?: SocialLink[];
}

export interface Relationship {
  id: string;
  creatorHandle: string;
  platform: Platform;
  liked: boolean;
  commented: boolean;
  followed: boolean;
  replied: boolean;
  invited: boolean;
  collaboratorScore: number;
  notes: string;
  influencerId: string | null;
  createdAt: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Organic-growth domain types (Instagram + TikTok)
// ---------------------------------------------------------------------------
//
// These power the features that actually move follower growth on IG/TikTok —
// your own short-form content, your own analytics, and the trend radar — as
// opposed to the outbound-engagement CRM above (find/comment on other creators).

// Content + Trends are scoped to the two short-form platforms we optimize for.
export const ContentPlatforms = ["instagram", "tiktok"] as const;
export type ContentPlatform = (typeof ContentPlatforms)[number];

export const ContentFormats = [
  "reel",
  "carousel",
  "talking-head",
  "tutorial",
  "story",
  "voiceover",
] as const;
export type ContentFormat = (typeof ContentFormats)[number];

export const ContentStatuses = ["idea", "drafting", "scheduled", "posted"] as const;
export type ContentStatus = (typeof ContentStatuses)[number];

// A planned/produced piece of content. Generated by the Content Studio and
// persisted as a draft the creator can iterate on, schedule, and mark posted.
export interface ContentIdea {
  id: string;
  topic: string;
  platform: ContentPlatform;
  format: ContentFormat;
  hook: string; // the chosen primary hook (first 1–3 seconds)
  hooks: string[]; // alternative hooks to A/B
  scriptBeats: string[]; // ordered beats / shot list
  caption: string;
  firstComment: string; // first-comment SEO / hashtag dump
  hashtags: string[];
  audioIdea: string; // trending-sound or audio direction
  cta: string; // call-to-action that drives follows / saves
  status: ContentStatus;
  scheduledFor: string | null;
  notes: string;
  createdAt: string;
  updatedAt: string;
}

// Trend Radar — sounds, formats, hashtags, and topics worth riding now.
export const TrendTypes = ["sound", "format", "hashtag", "topic"] as const;
export type TrendType = (typeof TrendTypes)[number];

export const TrendMomentums = ["rising", "peaking", "fading"] as const;
export type TrendMomentum = (typeof TrendMomentums)[number];

export interface Trend {
  id: string;
  platform: ContentPlatform;
  type: TrendType;
  title: string;
  description: string;
  momentum: TrendMomentum;
  exampleUrl: string | null;
  createdAt: string;
}

// My Growth — the creator's OWN accounts, follower history, and post analytics.
export interface MyAccount {
  id: string;
  platform: ContentPlatform;
  handle: string;
  displayName: string;
  followers: number; // latest known follower count
  createdAt: string;
  updatedAt: string;
}

export interface FollowerSnapshot {
  id: string;
  accountId: string;
  date: string; // ISO date of the reading
  followers: number;
  reach: number; // 0 when unknown
  profileViews: number; // 0 when unknown
  createdAt: string;
}

export interface MyPost {
  id: string;
  accountId: string;
  platform: ContentPlatform;
  title: string;
  format: ContentFormat;
  postedAt: string;
  reach: number;
  likes: number;
  comments: number;
  shares: number;
  saves: number;
  follows: number; // new follows attributed to this post
  createdAt: string;
}
